# Generated by hellwal

wallpaper='/home/levrone/.config/Wallpapers//a_landscape_of_mountains_and_blue_sky.png'

background='000000'
foreground='e8ffff'
cursor='e8ffff'
border='e8ffff'

color0='000000'
color1='000000'
color2='202020'
color3='202030'
color4='304050'
color5='5c8087'
color6='588288'
color7='add9ff'
color8='000000'
color9='000000'
color10='282828'
color11='28283c'
color12='3c5064'
color13='73a0a8'
color14='6ea2aa'
color15='e8ffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
