# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#000000\033\\"
printf "\033]4;1;#000000\033\\"
printf "\033]4;2;#202020\033\\"
printf "\033]4;3;#202030\033\\"
printf "\033]4;4;#304050\033\\"
printf "\033]4;5;#5c8087\033\\"
printf "\033]4;6;#588288\033\\"
printf "\033]4;7;#add9ff\033\\"
printf "\033]4;8;#000000\033\\"
printf "\033]4;9;#000000\033\\"
printf "\033]4;10;#282828\033\\"
printf "\033]4;11;#28283c\033\\"
printf "\033]4;12;#3c5064\033\\"
printf "\033]4;13;#73a0a8\033\\"
printf "\033]4;14;#6ea2aa\033\\"
printf "\033]4;15;#e8ffff\033\\"

# Background
printf "\033]11;#000000\033\\";

# Foreground
printf "\033]10;#e8ffff\033\\";

# Cursor
printf "\033]12;#e8ffff\033\\";

# Border
printf "\033]7044;#e8ffff\033\\";
